MAIN_URL = 'https://qa-desk.stand.praktikum-services.ru'
MAIN_AFTER_REGISTRATION_URL = f'{MAIN_URL}/regiatration'
CREATE_LISTING_URL = f'{MAIN_URL}/create-listing'
TEST_PASSWORD = 'password123'
ERROR_FORM_COLOR = 'rgb(255, 105, 114)'
EXISTING_USER_EMAIL = 'euser@example.com'
